config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root to: 'pages#home'
  get 'FAQ', to: 'pages#FAQ'
  patch 'users/:id/change_usertype', to: "users#change_usertype", as: :change_usertype
  get 'users/:id/dashboard', to: "users#dashboard", as: :dashboard
  get 'users/:id/show', to: "users#show", as: :profile


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :meals do
    resources :pictures, only: [:new, :create, :destroy]
    resources :reviews, only: [:new, :create, :destroy]
    resources :items, only: [:create]
  end

  resources :users, only: [:index]
  patch 'meals/:id/publish' , to: "meals#publish", as: :publish_meal


  resources :orders, only: [:index, :show, :create, :destroy] do
    member do
      get 'payment', to: 'payments#new'
      post 'payment', to: 'payments#create'
      get 'confirmation', to: 'payments#confirmation'
    end
  end
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo and searchbar-->
  <div class="navbar-wagon-left">

    <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= cl_image_tag'chef.svg'%>
    <% end %>

    <div class="searchbar">
      <%= form_tag meals_path, method: :get do %>
       <%= text_field_tag :query,
    params[:query],
    class: "form-control",
    placeholder: "search a city or dish (ex: chicken, casablanca...)"
    %>
    <% end %>
    </div>

  </div>

  <!-- Right Navigation on md and lg -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">


    <% if user_signed_in? %>


      <!-- Links when logged in as customer-->
      <% if current_user.usertype == "customer" %>
      <%= link_to "Browse Meals", "/meals", class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Become a Cook", change_usertype_path(current_user), method: :patch, class: "navbar-wagon-item navbar-wagon-link"%>
      <%= link_to "View Basket",order_path(current_user.orders.where(state: "pending")), method: :get, class: "navbar-wagon-item navbar-wagon-link"%>
      <%= link_to "My Orders", orders_path, method: :get, class: "navbar-wagon-item navbar-wagon-link"%>
      <% end %>

      <!-- Links when logged in as cook-->
      <% if current_user.usertype == "cook" %>
      <%= link_to "Post a New Meal", "/meals/new", class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "See my Meals", dashboard_path(current_user), class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Back to Customer Mode", change_usertype_path(current_user), method: :patch, class: "navbar-wagon-item navbar-wagon-link" %>

      <% end %>

      <!-- Links seen by all-->
      <%= link_to "FAQ", "/FAQ", class: "navbar-wagon-item navbar-wagon-link" %>

      <% if current_user.photo == nil  %> <!-- if user doesnt upload photo => default image -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= cl_image_tag "circled-user", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", 'data-toggle': "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">

            <li>
              <%= link_to profile_path(current_user) do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fas fa-sign-out-alt"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>

          </div>
        </div>

      <% else %> <!-- if user has a photo, then userpic -->
          <%= cl_image_tag current_user.photo, class: "avatarcustomized dropdown-toggle", id: "navbar-wagon-menu", 'data-toggle': "dropdown" %>
          <div class="badge"><%= current_user.usertype %></div>

          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">

            <li>
              <%= link_to profile_path(current_user) do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fas fa-sign-out-alt"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
      <% end %>

    <% else %>  <!-- case if user signed out -->

      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to t(".sign_up", default: "Sign up"), new_user_registration_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>


  <!-- Dropdown list appearing on mobile only -->




    <div class="navbar-wagon-item hidden-md hidden-lg">
      <% if user_signed_in? %> <!-- When user is signed in -->

        <% if current_user.usertype == "customer" %> <!-- signed in as a customer-->
          <div class="dropdown">
            <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
            <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
              <li> <%= link_to profile_path(current_user) do %>
                  <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
                  <% end %></li>
              <li> <%= link_to meals_path do %>
                  <i class="fas fa-utensils"></i> <%= t(".meals", default: "Meals") %>
                  <% end %></li>
              <li><%= link_to change_usertype_path(current_user), method: :patch do %>
                  <i class="fas fa-exchange-alt"></i>  <%= t(".change status cook/customer", default: "switch status") %>
                  <% end %></li>
              <li><%= link_to order_path(current_user.orders.where(state: "pending")), method: :get do %>
                  <i class="fas fa-shopping-basket"></i> <%= t(".view basket", default: "My basket") %>
                  <% end %></li>
              <li><%= link_to orders_path, method: :get do %>
                  <i class="fas fa-receipt"></i> <%= t(".view orders", default: "My orders") %>
                  <% end %></li>
              <li><%= link_to destroy_user_session_path, method: :delete do %>
                  <i class="fas fa-sign-out-alt"></i>  <%= t(".sign_out", default: "Log out") %>
                  <% end %></li>
            </ul>
          </div>

          <% else %> <!-- signed in as a cook-->
            <div class="dropdown">
              <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
              <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
                <li> <%= link_to profile_path(current_user) do %>
                    <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
                  <% end %></li>
              <li> <%= link_to meals_path do %>
                  <i class="fas fa-utensils"></i> <%= t(".meals", default: "Meals") %>
                  <% end %></li>
                <li><%= link_to change_usertype_path(current_user), method: :patch do %>
                    <i class="fas fa-exchange-alt"></i>  <%= t(".change status cook/customer", default: "switch status") %>
                  <% end %></li>
                <li><%= link_to new_meal_path do %>
                    <i class="fas fa-plus-circle"></i>  <%= t(".post new meal", default: "post a new meal") %>
                  <% end %></li>
                <li><%= link_to dashboard_path(current_user) do %>
                    <i class="fas fa-folder-open"></i>  <%= t(".my meals", default: "my meals") %>
                  <% end %></li>
                <li><%= link_to destroy_user_session_path, method: :delete do %>
                    <i class="fas fa-sign-out-alt"></i>  <%= t(".sign_out", default: "Log out") %>
                  <% end %></li>
              </ul>
            </div>
          <% end %>


      <% else %> <!-- When user is signed out -->
        <div class="dropdown">
          <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li><a href="/meals">View Meals</a></li>
            <li><a href="/users/sign_up">Sign up</a></li>
            <li><a href="/users/sign_in">Log In</a></li>
          </ul>
        </div>
      <% end %>
    </div>

</div>