config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root to: 'pages#home'
  get 'FAQ', to: 'pages#FAQ'
  patch 'users/:id/change_usertype', to: "users#change_usertype", as: :change_usertype
  get 'users/:id/dashboard', to: "users#dashboard", as: :dashboard
  get 'users/:id/show', to: "users#show", as: :profile


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :meals do
    resources :pictures, only: [:new, :create, :destroy]
    resources :reviews, only: [:new, :create, :destroy]
    resources :items, only: [:create]
  end

  resources :users, only: [:index]
  patch 'meals/:id/publish' , to: "meals#publish", as: :publish_meal


  resources :orders, only: [:index, :show, :create, :destroy] do
    member do
      get 'payment', to: 'payments#new'
      post 'payment', to: 'payments#create'
      get 'confirmation', to: 'payments#confirmation'
    end
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :items, dependent: :destroy
  monetize :amount_cents

  validates :state, presence: true, inclusion: { in: ["pending", "deleted", "paid"]}
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  after_action :authorize_order, only: [:new, :show, :create, :destroy]

  def index
    @orders = policy_scope(Order).where(user: current_user)
    @reviews_by_user = Review.where(user: current_user)

    @meals_reviewed_by_user = []
    @reviews_by_user.each do |review|
      @meals_reviewed_by_user << review.meal
    end
  end

  def new
    @order = Order.new
  end

  def show
    #@order = Order.find(params[:id])
    @order = current_order
    @subtotals = []
      @order.items.each do |item|
        @subtotals << item.meal.price * item.quantity
      end
    @total = @subtotals.sum
    @order.update(amount: @total, state: 'pending')
    @order
  end

  def create
    @user = current_user
    @meal = Meal.find(params[:meal_id])
    @order = Order.create!(amount: @meal.price, state: 'pending', user: current_user)
    redirect_to order_path(@order)
  end

  def destroy
    @order = current_user.orders.last
    @order.state = "deleted"
    @order.destroy
      if @order.destroyed?
        flash[:notice] = "Your order was deleted successfully! :)"
        redirect_back(fallback_location: root_path)
      else
        flash[:notice] = "There was an error. Please try again. :("
        redirect_back(fallback_location: root_path)
      end
  end

  private

  def order_params
    params.require(:order).permit(:meal_id, :url)
  end

  def authorize_order
   authorize @order
  end
end

app/views/orders/create.html.erb
<h1>Orders#create</h1>
<p>Find me in app/views/orders/create.html.erb</p>

app/views/orders/destroy.html.erb
<h1>Orders#destroy</h1>
<p>Find me in app/views/orders/destroy.html.erb</p>

app/views/orders/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">

      <% if @orders == [] %>
        <div class="text-center">
          <h1>You have not made any order yet</h1>
          <h1><i class="fas fa-shopping-basket"></i></h1>
          <div>
           <%= link_to 'Browse Meals', meals_path, class: "btn btn-success" %>
          </div>
        <div>

      <% else %>
        <h1 class="coloredh1">My Orders</h1>
            <% @orders.reverse.each do |order| %>


              <!-- order card -->
              <div class="col-xs-12 col-sm-6 col-md-4">
                <div class="mealreviews">

                  <div class="mealreviewsheaders">
                  <h4>Date: <%= order.updated_at.strftime("%d/%m/%Y") %></h4>
                  </div>

                  <div class="#mealreviewscontentleft">
                  <% order.items.each do |item| %>

                        <ul>
                        <li><%= link_to item.meal.title, meal_path(item.meal) %>: <%=item.quantity %> </li>
                        </ul>

                        <div class = "alignedbuttonsbox">
                          <div>
                            <%= cl_image_tag item.meal.user.photo, class: "avatarcustomized" %>
                            <%= item.meal.user.username%>
                          </div>
                          <div>
                            <% if !@meals_reviewed_by_user.include? item.meal %>
                            <p><%= link_to "Leave this cook a review", new_meal_review_path(item.meal), class: "btn  btn-success" %></p>
                            <% else %>
                            <p>You have already reviewed this meal!</p>
                            <% end %>
                          </div>
                        </div>

                        <br>

                        <div class="customitemalignedright">
                        <p > Sub-total <%= humanized_money_with_symbol(item.meal.price * item.quantity)%> </p>
                        </div>

                    <% end %>

                    <br>

                      <div class="customitemalignedright">
                      <h4> Order total: <%= humanized_money_with_symbol(order.amount_cents/100)%> </h4>
                      <p> Payment status: <%= order.state%> </p>

                        <% if order.state != "paid" %>
                        <%= link_to "Proceed to Payment", payment_order_path(order), class: "btn  btn-success" %>
                        <%= link_to 'Delete order', order_path(order.id), method: :delete, class: "btn btn-danger"%>
                        <%end %>
                      </div>
                  </div>
            </div>
          </div>
<!-- end of order card if there are any -->
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/orders/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">

        <% if @order.id.nil? %>
        <div class= "text-center">
          <h1>Your basket is empty.</h1>
          <h1><i class="fas fa-shopping-basket"></i></h1>
          <div>
           <%= link_to 'Browse Meals', meals_path, class: "btn btn-success" %>
          </div>
        </div>

        <% else %>
        <div>
            <% @order.items.each do |item| %>
            <article class="product">
              <header>
              <div class="meal-card-image" style="background-image: url('<%= cl_image_path item.meal.pictures.first.url.url %>');">
              </div>
              </header>
                <div>
                  <h1><%= item.meal.title %></h1>
                  <p><%= item.meal.description %></p>
                  <p> Quantity: <%= item.quantity %></p>
                  <p> total: <%= item.meal.price * item.quantity %> </p>
                </div>
            </article>
            <% end %>

            <div class= "coloredh1">
              <h1>Total: <%= @total %>DHS</h1>
            </div>

            <div class= "alignedbuttonsboxcenter">
              <div>
                <%= link_to 'Delete order', order_path(@order.id), method: :delete, class: "btn btn-danger"%>
              </div>
              <div>
                <%= link_to 'Checkout', payment_order_path, class: "btn btn-success" %>
              </div>
              <div>
                <%= link_to 'Back to Meals', meals_path, class: "btn btn-success" %>
              </div>
            </div>

          </div>
        <% end %>

    </div>
  </div>
</div>