config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root to: 'pages#home'
  get 'FAQ', to: 'pages#FAQ'
  patch 'users/:id/change_usertype', to: "users#change_usertype", as: :change_usertype
  get 'users/:id/dashboard', to: "users#dashboard", as: :dashboard
  get 'users/:id/show', to: "users#show", as: :profile


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :meals do
    resources :pictures, only: [:new, :create, :destroy]
    resources :reviews, only: [:new, :create, :destroy]
    resources :items, only: [:create]
  end

  resources :users, only: [:index]
  patch 'meals/:id/publish' , to: "meals#publish", as: :publish_meal


  resources :orders, only: [:index, :show, :create, :destroy] do
    member do
      get 'payment', to: 'payments#new'
      post 'payment', to: 'payments#create'
      get 'confirmation', to: 'payments#confirmation'
    end
  end
end

app/models/meal.rb
class Meal < ApplicationRecord
  belongs_to :user

  include PgSearch
  pg_search_scope :global_search,
    against: [:title, :description],
    associated_against: {
        user: [:address]
        },
    using: {
      tsearch: { prefix: true }
    }

  has_many :pictures
  has_many :reviews
  accepts_nested_attributes_for :pictures

  monetize :price_cents

  validates :title, presence: true
  validates :price, presence: true
  validates :description, presence: true, length: { minimum: 10 }
  validates :category, presence: true, inclusion: { in: ["appetizer", "main course", "dessert", "side", "other"]}

  # def self.published(meals)
  #   meals.where(published: true)
  # end

  # def unpublished
  #   self.where(published: false)
  # end
end

app/controllers/meals_controller.rb
class MealsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  after_action :authorize_meal, only: [:new, :create, :edit, :update, :destroy, :dashboard, :show, :publish ]

  def index
    if params[:query].present?
      @meals = policy_scope(Meal).global_search(params[:query])
    else
      @meals = policy_scope(Meal).order(created_at: :desc)
    end

    @cooks = @meals.map { |meal| meal.user unless meal.user.nil? && meal.user.latitude.nil? }

    @markers = @cooks.map do |cook|
      {
        lng: cook.longitude,
        lat: cook.latitude,
        infoWindow: {
          content: render_to_string(partial: "/users/map_window", locals: { user: cook })
        }
      }
    end
  end

  def show
    @meal = Meal.find(params[:id])
    @order = Order.new
    @customer = current_user
    @cook = @meal.user
    @item = Item.new
    unpublish_when_soldout
  end

  def new
    @meal = Meal.new
  end

  def create
    @meal = Meal.new(meal_params)
    @meal.published = true
    @meal.user = current_user
    if @meal.save
      redirect_to new_meal_picture_path(@meal)
    else
      render :new
    end
  end

  def publish
    @meal = Meal.find(params[:id])
    if @meal.published
      @meal.published = false
    else
      @meal.published = true
    end
    @meal.save

    redirect_to meal_path(@meal)
  end

  def unpublish_when_soldout
    @meal.published = false if @meal.maxservings.nil?
  end

  def edit
    @meal = Meal.find(params[:id])
  end

  def update
    @user = current_user
    @meal = Meal.find(params[:id])
    @meal.user = current_user
    if @meal.update(meal_params)
      redirect_to dashboard_path(@user)
    else
      render :edit
    end
  end

  def destroy
    # let's not delete meals, just unpublish
  end

  def dashboard
  end

  private

  def meal_params
    params.require(:meal).permit(:id, :title, :user, :description, :address, :published, :price, :maxservings, :category, pictures_attributes: [:id, :meal_id, :url])
  end

  def authorize_meal
    authorize @meal
  end
end

app/views/meals/destroy.html.erb
<h1>Meals#destroy</h1>
<p>Find me in app/views/meals/destroy.html.erb</p>

app/views/meals/edit.html.erb
<div class="banner_meal">
  <div class="container" >
    <div class="row">

      <div class="col-xs-12 col-sm-6 col-sm-offset-3" id="signup-form">
        <%= simple_form_for(@meal) do |f| %>
        <% if @meal.errors.any? %>
          <% @meal.errors.full_messages.each do |m| %>
            <p><%= m %></p>
          <% end %>
        <% end %>
        <h1>Edit your Meal</h1>
        <br>
          <%= f.input :title %>
          <%= f.input :price, label: "Price"%>
          <%= f.input :category, as: :select, label: "Category", collection: ["appetizer", "main course", "dessert", "side", "other"]%>
          <%= f.input :description, label: 'Meal Description' %>
          <%= f.input :maxservings, label: 'Max Servings' %>
          <%= f.input :shelflife, label: 'Shelf Life (Days)' %>
          <br>
          <%= f.submit "Update", class: "btn btn-success" %>
        <% end %>
        <br>
      </div>
    </div>
  </div>
</div>

app/views/meals/index.html.erb
<div class="container-fluid">
  <div class= "row">

        <!-- Cards -->
          <div class="col-sm-7">

            <!-- full map button only visible on xs screens -->
            <div class="visible-xs-block">
              <%= link_to 'click here for map view', users_path, class: "btn btn-success map-button" %>
            </div>

            <% @meals.where(published: true).each do |meal| %>
              <div class="col-xs-12 col-sm-6 col-md-4">
                <div class="meal-card">
                  <div class="meal-card-image" style="background-image: url('<%= cl_image_path meal.pictures.first.url.url %>');">
                  </div>
                    <div class="meal-card-content">
                      <div class="meal-card-title">
                        <h4><%= meal.title %></h4>
                        <p> <i class="fas fa-utensils"></i> <%= meal.category %></p>
                      </div>
                      <div class="flex">
                        <p>Price: <%= humanized_money_with_symbol(meal.price) %>
                        </p>
                      </div>
                    </div>
                    <%= link_to '', meal_path(meal), class: "card-link" %>
                </div>
              </div>
            <% end %>
          </div>

        <!-- Map -->
          <div class="col-sm-5 hidden-xs">

            <div>
              <%= link_to 'View Map Full Screen', users_path, class: "btn btn-success map-button" %>
            </div>

            <div
              id="map"
              style="width: 100%; height: 100vh;"
              data-markers="<%= @markers.to_json %>"
              data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
            >
            </div>
          </div>
  </div>
</div>



<% content_for :scripts do %>
  <%= javascript_pack_tag "map" %>
<% end %>

app/views/meals/new.html.erb
<div class="banner_meal">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-10 col-sm-offset-1 col-md-8 col-sm-offset-2" id="signup-form">
        <%= simple_form_for(@meal) do |f| %>
        <% if @meal.errors.any? %>
          <% @meal.errors.full_messages.each do |m| %>
            <p><%= m %></p>
          <% end %>
        <% end %>
        <h1>Post a New Meal</h1>

          <%= f.input :title %>
          <%= f.input :price, label: "Price"%>
          <%= f.input :category, as: :select, label: "Category", collection: ["appetizer", "main course", "dessert", "side", "other"]%>
          <%= f.input :description, label: 'Meal Description' %>
          <%= f.input :maxservings, label: 'Max Servings' %>
          <%= f.input :shelflife, label: 'Shelf Life (Days)' %>

          <%= f.submit "Submit Meal", class: "btn btn-success" %>
        <% end %>

      </div>
    </div>
  </div>
</div>

app/views/meals/show.html.erb
<div class="container">
  <div class="row">

    <!-- left column -->
    <div class="col-xs-12 col-sm-6">
      <div class="coloredh1">
        <h1>The Meal</h2>
      </div>
    <!-- meal card -->
      <div class="mealreviews text-center">

        <!-- meal pic -->

        <div class="meal-card-image" style="background-image: url('<%= cl_image_path @meal.pictures.first.url.url %>');">
        </div>

        <!-- meal details -->
        <div class="profile-info">
          <h1><%= @meal.title %></h1>
              <div>
                    <div class="mealinfo">
                        <h2> <%= @meal.description %></h2>
                        <h4>Available servings:   <%= @meal.maxservings %></h4>
                        <h4>Price per portion:    <%= humanized_money_with_symbol(@meal.price) %></h4>
                        <h4>Ready in 30 minutes</h4>

                        <!-- buttons and options -->
                        <% unless @meal.published %>
                          <h3>This meal is not currently available</h3>
                        <% end %>

                        <% if user_signed_in? && @meal.user == current_user   %>
                          <div class="alignedbuttonsbox">
                              <div>
                              <%= link_to @meal.published ? "Unpublish" : "Publish!", publish_meal_path(@meal), method: :patch, class: "btn btn-success orderbtn" %>
                              </div>

                              <div>
                              <%= link_to 'Edit this meal', edit_meal_path(@meal), class: "btn btn-success" %>
                              </div>
                          </div>
                        <% end %>

                        <div>
                          <% if user_signed_in? && current_user.usertype == 'customer' && @meal.user != current_user %>
                          <h2>Please select number of servings:</h2>
                            <div >
                              <%= form_tag(meal_items_path(@meal), method: "post") do %>
                                  <div class='alignedbuttonsbox'>
                                  <%= number_field_tag(:quantity, nil, min: 0, max: @meal.maxservings) %>
                                  <%= submit_tag("Add to Order", class: "btn btn-success") %>
                                  </div>
                              <% end %>
                            </div>
                          <% end %>
                          </div>

                        <% if !user_signed_in? %>
                          <div>
                            <%= link_to 'Sign in to order', new_user_session_path, class: "btn  btn-success" %>
                          </div>
                        <% end %>
                </div>
            </div>
        </div>
      </div>
    </div>     <!-- end of left column -->



    <!-- right column -->
    <div class="col-xs-12 col-sm-6">

      <div class="coloredh1">
        <h1>The Cook</h2>
      </div>

      <!-- cook profile -->
      <div class="mealreviews">



        <div class="mealreviewscontent" >
           <!-- cook or user avatar -->
          <div>
            <% if user_signed_in? %>
              <%= link_to profile_path(@cook) do %>
              <%= cl_image_tag @cook.photo, class: "mediumavatar"%>
              <% end %>
            <% else %>
              <%= cl_image_tag @cook.photo, class: "mediumavatar"%>
            <% end %>
          </div>


          <div> <!-- cook or user name -->
          <% if @meal.user == current_user %>
            <h2> My Public Profile</h2>
          <% else %>
            <h2> <%= @cook.username.capitalize %></h2>
          <% end %>
                <p>member since :<%= @cook.created_at.strftime("%d/%m/%Y") %></p>
          </div>

       </div>


        <div class="mealreviewsheaders">
          <h2>Reviews from customer</h2>
        </div>

        <div class="mealreviewscontent" id="mealreviewscontentleft">
          <% if @cook.cook_reviews == [] %>
            <p>This cook has no reviews yet.</p>
          <% else  %>
            <% @cook.cook_reviews.each do |review|%>
                <div class="innermealreviews customizemalignedleft" >
                   <strong> <span style="color: #27b896; font-size: 25px;"><%= '*' * review.rating.to_i %></span> </strong>
                   <p>"<%=review.content %>"</p>
                </div>
                <% end %>
          <% end %>
        </div>

      </div>

      <!-- this cook's other meals -->
      <div class="mealreviews">

        <div class="mealreviewsheaders">
          <% if @meal.user == current_user %>
            <h2> My Meals</h2>
          <% else %>
            <h2> all meals by <%= @cook.username.capitalize %> </h2>
          <% end %>
        </div>

        <div class="mealreviewscontent" id="mealreviewscontentleft">
          <% @cook.meals.each do |meal| %>
                <div class="small-meal-card">
                  <div class="small-meal-card-image" style="background-image: url('<%= cl_image_path meal.pictures.first.url.url %>');">
                  </div>
                  <div class="small-meal-card-content">
                    <div class="meal-card-title">
                      <h4><%= link_to meal.title, meal_path(meal), :class => "text-dark" %></h4>
                      <p><%= meal.category %></p>
                      <p><i class="fas fa-utensils"></i>
                      Price: <%= humanized_money_with_symbol(meal.price) %>
                      </p>
                    </div>
                  </div>
                </div>
          <% end %>
        </div>

      </div>


    </div>    <!-- end of right column -->

  </div>     <!-- end of row -->
</div>     <!-- end of container -->

app/views/meals/update.html.erb
<h1>Meals#update</h1>
<p>Find me in app/views/meals/update.html.erb</p>